### ISSUE TITLE
コミットメッセージがリリースノートに表示されない

### ISSUE THREAD

**Issue by honma-ambient** [ambient-lab/ambient-tmpl-root#104]
リリースノートの本文にに変更・追加したコミットメッセージが出力されない

現状のリリースノート出力結果
https://github.com/ambient-lab/ambient-tmpl-root/releases/tag/v0.0.1

**Comment by k-onodera-ambient** [comment]
作業メモ

release.yaml
```
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
```

ここでrelease noteを作成している。本文はbodyで、値には`steps.tag_version.outputs.changelog`を入れている
tag_version は https://github.com/mathieudutour/github-tag-action/tree/releases/v3
outputsをみてみるとchangelogの項目はなかったのでstepsを追加して別途作成する必要がある
![image](https://github.com/ambient-lab/ambient-tmpl-root/assets/141118878/48271eab-bde2-45e8-ad92-ff5ab900696f)
