### ISSUE TITLE
feat: dependabotの対象パッケージの設定の検討

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-root#170]
## 詳細

dependabotの対象パッケージなので設定の検討して、
最強設定にする。

## 期待する動作

_新しい仕様・機能が実装された場合、どのような動作を期待しているかを明示してください。_

## 実装アイデア

_仕様・機能の実装に関するアイデアや提案を共有してください。_

## 関連する情報

_関連するドキュメント、スクリーンショット、または参考情報がある場合、こちらにアップロードまたはリンクを貼ってください。_

**Comment by honma-ambient** [comment]
memo

- 基本利用するパッケージ群はあらかじめ用意する。
- それ以外で追加したい場合は、各プロジェクトで適宜設定する。go, maven, gradle, swiftなど


dependabot対象の使用するパッケージマネージャー
[package-ecosystem](https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)



- root
  - なし
- web
  - npm, pip
- web-tw
  - npm, pip
- web-mui
  - npm, pip
- app
  - npm, pip
- infra
  - npm, pip

**Comment by honma-ambient** [comment]
### 通知のタイミングどうするか？

一旦、毎週月曜日の10:00に１回実施とする



間隔の型 | 頻度
-- | --
daily | 月曜日から金曜日までのすべての平日に実行します。
weekly | 毎週 1 回実行します。 デフォルトでは月曜日に設定されています。 これを変更するには、schedule.day を使います。
monthly | 毎月 1 回実行します。 その月の最初の日に設定されています。


```
    schedule:
      interval: "weekly"
      time: "09:00"
      # Use Japan Standard Time (UTC +09:00)
      timezone: "Asia/Tokyo"
```
